### ISSUE TITLE
Add to Collection: Not needed any more

### ISSUE THREAD

**Issue by davidhedlund** [jvillalobos/Add-to-Collection#2]
AMO now includes the old functionality to add add-ons directly on their page. I assume that **you** fixed this: Thanks!

Example: I added [DuckDuckGo Privacy Essentials ](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/)

![screenshot from 2018-02-05 02 30 35](https://user-images.githubusercontent.com/6416073/35784894-902d6252-0a1c-11e8-978a-c2e72a353ed6.png)

With this said, can you please update the text in [Add to Collection ](https://addons.mozilla.org/en-US/firefox/addon/add-to-collection/) to mention if this add-on is deprecated?

**Comment by jvillalobos** [comment]
I'll just hide the listing. Thanks for letting me know. I'm also glad that the feature is back.

**Comment by davidhedlund** [comment]
> I'm also glad that the feature is back.

Dito.
